#ifndef CONFIG_H
#define CONFIG_H

#define TOTAL_INTERRUPTS 512
#define KERNEL_CODE_SELECTOR 0x08
#define KERNEL_DATA_SELECTOR 0x10

#define ZHIOS_HEAP_SIZE_BYTES 104857600
#define ZHIOS_HEAP_BLOCK_SIZE 4096

#define ZHIOS_DISK_SECTOR_SIZE 512

#define ZHIOS_MAX_PATH 100

#define ZHIOS_MAX_FILE_SYSTEMS 12
#define ZHIOS_MAX_FILE_DESCRIPTORS 256

#define ZHIOS_TOTAL_GDT_SEGMENTS 6

#define ZHIOS_PROGRAM_VIRTUAL_ADDRESS 0x400000
#define ZHIOS_PROGRAM_STACK_SIZE 1024 * 16
#define ZHIOS_PROGRAM_VIRTUAL_STACK_ADDRESS_START 0x3FF000
#define ZHIOS_PROGRAM_VIRTUAL_STACK_ADDRESS_END ZHIOS_PROGRAM_VIRTUAL_STACK_ADDRESS_START - ZHIOS_PROGRAM_STACK_SIZE
#define ZHIOS_PROCESS_MAX_ALLOCATIONS 1024
#define ZHIOS_MAX_PROCESS 64

#define USER_DATA_SEGMENT 0x23
#define USER_CODE_SEGMENT 0x1B

#define ZHIOS_MAX_ISR80H_COMMANDS 1024

#endif
